robot:
  optimization:
    enabled: true
    ratio: '10:80:10'
    short_distance: 100
    short_distance_ratio: '30:40:30' #[100]
  gripper:
    take_angle: 160
    release_angle: 75
    step: 5
    delay: 50 #ms
    check_phase: true
  speed:
    xy: 10000
    xy_slow: 1000
    z: 15000
    z_slow: 1000
  timer:
    enabled: true
    x: 450
    y: 140
    z: -60
    y_b: 220
  board:
    x: -184
    y: 210
    z: -85
    safe_z: 20
    figure_z: -50
    square_size: 46
  out:
    x: 400
    y: 50
    z: -60
  in:
    x: 400
    y: 0
  buzzer:
    duration: 1000 #ms
    pwm: 0.1 #0<pwm<1
# control robot via mqtt
broker:
  enabled: True
  url: 127.0.0.1
  port: 1883
  topic:
    request: api/request
    response: api/response

klipper:
  socket: /tmp/klippy_uds

app:
  chess_engine:
    level: 9