robot:
  optimization:
    enabled: true
    ratio: '10:80:10'
    short_distance: 100
    short_distance_ratio: '30:40:30' #[100]
  gripper:
    take_angle: 163
    release_angle: 95
    step: 5
    delay: 200 #ms
    check_phase: true
  speed:
    xy: 10000
    xy_slow: 1000
    z: 8000
    z_slow: 1000
  timer:
    enabled: true
    x: -95
    y: 90
    z: -50
    y_b: 220
  board:
    x: -184
    y: 210
    z: -80
    safe_z: 20
    figure_z: -50
    square_size: 41
    margin_size: 20
  out:
    x: 400
    y: 50
    z: -60
  in:
    x: 400
    y: 0
  buzzer:
    beep_duration: 100 #ms
    pwm: 0.1 #0<pwm<1
    beep_times: 3
# control robot via mqtt
broker:
  enabled: False
  url: 192.168.1.19
  port: 1883
  topic:
    request: api/request
    response: api/response

klipper:
  socket: /tmp/klippy_uds

app:
  chess_engine:
    level: 9