robot:
  gripper:
    take_angle: 140
    release_angle: 85
  speed:
    xy: 15000
    z: 8000
    z_slow: 4000
  timer:
    x: 450
    y: 140
    z: -60
    y_b: 220
  board:
    x: -184
    y: 210
    z: -100
    safe_z: 20
    square_size: 46
  out:
    x: 400
    y: 50
  in:
    x: 400
    y: 0
# control robot via mqtt
broker:
  enabled: True
  url: 127.0.0.1
  port: 1883
  topic:
    request: api/request
    response: api/response

klipper:
  socket: /tmp/klippy_uds