robot:
  gripper:
    take_angle: 125
    release_angle: 85
  speed:
    xy: 12000
    z: 5000
    z_slow: 1200
  timer:
    x: 450
    y: 140
    z: -48
  board:
    x: -184
    y: 210
    z: -65
    safe_z: 20
    square_size: 46
  out:
    x: 380
    y: 50
  in:
    x: 380
    y: 0
# control robot via mqtt
broker:
  enabled: True
  url: 127.0.0.1
  port: 1883
  topic:
    request: api/request
    response: api/response

klipper:
  socket: /tmp/klippy_uds