robot:
  optimization:
    enabled: true
    ratio: '5:90:5'
    short_distance: 40
    short_distance_ratio: '30:40:30' #[100]
  gripper:
    take_angle: 110
    release_angle: 75
    step: 5
    delay: 200 #ms
    check_phase: true
  speed:
    xy: 8000
    xy_slow: 1000
    z: 4000
    z_slow: 1000
  timer:
    enabled: false
    x: -105
    y: 90
    z: -80
    y_b: 220
  board:
    x: -164 # 
    y: 250
    z: -118
    safe_z: 20
    figure_z: -54
    square_size: 41
    margin_size: 20
  out:
    # x: 400
    x: -115
    y: 180
    z: -60
  in:
    x: -115
    y: 270
  tissue:
    x: -115
    y: 30
    z: -70
  buzzer:
    beep_duration: 100 #ms
    pwm: 0.1 #0<pwm<1
    beep_times: 3
  urls:
    klipper: http://192.168.1.45:8000

# control robot via mqtt
broker:
  enabled: True
  url: 192.168.1.45
  port: 1883
  topic:
    request: api/request
    response: api/response

klipper:
  socket: /tmp/klippy_uds

urls:
  klipper: http://192.168.1.45:8000
  cam_board: http://192.168.1.153:8080
  cam_timer: http://192.168.118.200:8080

app:
  chess_engine:
    level: 20