path: /mnt/d/work/kingslayer/
train: ./datasets_640/train
val: ./datasets_640/val
test: ./datasets_640/test
nc: 12 # Number of classes (["Pawn", "Bishop", "King", "Queen", "Rook", "Knight"])x black or white
names:  ["Pw0", "Bs0", "Kg0", "Qn0", "Rk0", "Kt0", "Pw1", "Bs1", "Kg1", "Qn1", "Rk1", "Kt1"]

batch_size: 16
epochs: 100
# grayscale_conversion: True
data_augmentation: False
img_size: 640
augmentations:
  hsv_h: 0  # image HSV-Hue augmentation (fraction)
  hsv_s: 0    # image HSV-Saturation augmentation (fraction)
  hsv_v: 0    # image HSV-Value augmentation (fraction)
  degrees: 0  # image rotation (+/- degrees)
  translate: 0.2  # image translation (+/- fraction)
  scale: 0.5    # image scale (+/- gain)
  shear: 0.09    # image shear (+/- degrees)
  perspective: 0  # image perspective (+/- fraction), range 0-0.001
  flipud: 0   # image flip up-down (probability)
  fliplr: 0.5   # image flip left-right (probability)
  mosaic: 0.2   # image mosaic (probability)
  mixup: 0.2    # image mixup (probability)
  brightness: 0.1  # brightness augmentation
  contrast: 0.1    # contrast augmentation
  noise: 0.2      # noise augmentation (you might need to customize this if not available)